FROM apache/airflow:2.8.1-python3.10

USER root

# Install system dependencies required for GeoPandas and OSMnx
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    libspatialindex-dev \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copy requirements and install
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
